spring.application.name=ecommerce-backend

spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce-db

# JWT Configuration
jwt.secret=7d42cf3b2a1a44c59f8992a0d1b918764a8563c6d79a2f7c0a9693992b8d03c2
jwt.expiration=86400000

# Server Port
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.security=DEBUG
